const fs = require('fs');
const path = require('path');
const p = path.join('c:', 'Users', 'izaca', 'glithex-dev-backup', 'app', 'frontend-dev', 'src', 'i18n', 'translations.ts');
let content = fs.readFileSync(p, 'utf8');

const keys = {
  en: `    checkout_protocol_title: 'CHECKOUT PROTOCOL',
    checkout_step_1: '1. PHYSICAL COORDINATES',
    checkout_step_2: '2. FINANCIAL UPLINK (PAYMENT)',
    checkout_step_3: '3. FINAL VERIFICATION',
    checkout_email_label: 'COM-LINK (EMAIL)',
    checkout_fname_label: 'PRIMARY IDENTIFIER (NAME)',
    checkout_lname_label: 'CLONE IDENTIFIER (LAST NAME)',
    checkout_address_label: 'EXACT COORDINATES (STREET & NUMBER)',
    checkout_postal_label: 'SECTOR CODE (ZIP)',
    checkout_city_label: 'URBAN CORE (CITY)',
    checkout_country_label: 'TERRITORY (COUNTRY)',
    checkout_phone_label: 'CONTACT NETWORK (PHONE)',
    checkout_validate_btn: 'VALIDATE COORDINATES',
    checkout_shipping_promise: 'Logistics networks guarantee deployment as soon as possible.',
    checkout_inventory_title: 'IN YOUR INVENTORY',
    checkout_subtotal_label: 'Subtotal',
    checkout_shipping_label: 'Transfer Freight',
    checkout_total_label: 'Physical Total',
    checkout_qty: 'QTY',
    checkout_size: 'SIZE',
    checkout_success_title: 'TRANSMISSION CONFIRMED',
    checkout_success_desc: 'Your coordinates have been assimilated. Tactical assets are en route.',
    checkout_back_system: 'RETURN TO SYSTEM',
    checkout_back_cart: 'BACK TO CART',

`,
  es: `    checkout_protocol_title: 'PROTOCOLO DE SALIDA',
    checkout_step_1: '1. COORDENADAS FÍSICAS',
    checkout_step_2: '2. UPLINK FINANCIERO (PAGO)',
    checkout_step_3: '3. VERIFICACIÓN FINAL',
    checkout_email_label: 'COM-LINK (CORREO ELECTRÓNICO)',
    checkout_fname_label: 'IDENTIFICADOR PRINCIPAL (NOMBRE)',
    checkout_lname_label: 'CLON IDENTIFICADOR (APELLIDOS)',
    checkout_address_label: 'COORDENADAS EXACTAS (CALLE Y NÚMERO)',
    checkout_postal_label: 'CÓDIGO SECTOR (C.P.)',
    checkout_city_label: 'NÚCLEO URBANO (CIUDAD)',
    checkout_country_label: 'TERRITORIO (PAÍS)',
    checkout_phone_label: 'RED DE CONTACTO (TELÉFONO)',
    checkout_validate_btn: 'VALIDAR COORDENADAS',
    checkout_shipping_promise: 'Las redes de logística garantizan el despliegue lo antes posible.',
    checkout_inventory_title: 'EN TU INVENTARIO',
    checkout_subtotal_label: 'Subtotal',
    checkout_shipping_label: 'Flete de Transferencia',
    checkout_total_label: 'Total Físico',
    checkout_qty: 'CANT',
    checkout_size: 'TALLA',
    checkout_success_title: 'TRANSMISIÓN CONFIRMADA',
    checkout_success_desc: 'Tus coordenadas han sido asimiladas. Los activos tácticos están en ruta hacia tu localización.',
    checkout_back_system: 'VOLVER AL SISTEMA',
    checkout_back_cart: 'VOLVER AL CARRITO',

`,
  fr: `    checkout_protocol_title: 'PROTOCOLE DE SORTIE',
    checkout_step_1: '1. COORDONNÉES PHYSIQUES',
    checkout_step_2: '2. UPLINK FINANCIER (PAIEMENT)',
    checkout_step_3: '3. VÉRIFICATION FINALE',
    checkout_email_label: 'COM-LINK (EMAIL)',
    checkout_fname_label: 'IDENTIFIANT PRINCIPAL (PRÉNOM)',
    checkout_lname_label: 'CLONE IDENTIFIANT (NOM ADDITIONNEL)',
    checkout_address_label: 'COORDONNÉES EXACTES (RUE & NUMÉRO)',
    checkout_postal_label: 'CODE SECTEUR (CODE POSTAL)',
    checkout_city_label: 'NOYAU URBAIN (VILLE)',
    checkout_country_label: 'TERRITOIRE (PAYS)',
    checkout_phone_label: 'RÉSEAU DE CONTACT (TÉLÉPHONE)',
    checkout_validate_btn: 'VALIDER LES COORDONNÉES',
    checkout_shipping_promise: 'Les réseaux logistiques garantissent le déploiement dès que possible.',
    checkout_inventory_title: 'DANS VOTRE INVENTAIRE',
    checkout_subtotal_label: 'Sous-total',
    checkout_shipping_label: 'Fret de transfert',
    checkout_total_label: 'Total Physique',
    checkout_qty: 'QTÉ',
    checkout_size: 'TAILLE',
    checkout_success_title: 'TRANSMISSION CONFIRMÉE',
    checkout_success_desc: 'Vos coordonnées ont été assimilées. Les actifs tactiques sont en route.',
    checkout_back_system: 'RETOURNER AU SYSTÈME',
    checkout_back_cart: 'RETOUR AU PANIER',

`,
  de: `    checkout_protocol_title: 'CHECKOUT-PROTOKOLL',
    checkout_step_1: '1. PHYSISCHE KOORDINATEN',
    checkout_step_2: '2. FINANZ-UPLINK (ZAHLUNG)',
    checkout_step_3: '3. ABSCHLUSSPRÜFUNG',
    checkout_email_label: 'COM-LINK (E-MAIL)',
    checkout_fname_label: 'HAUPTIDENTIFIKATOR (VORNAME)',
    checkout_lname_label: 'KLON-IDENTIFIKATOR (NACHNAME)',
    checkout_address_label: 'EXAKTE KOORDINATEN (STRAẞE & NUMMER)',
    checkout_postal_label: 'SEKTORCODE (PLZ)',
    checkout_city_label: 'URBANER KERN (STADT)',
    checkout_country_label: 'TERRITORIUM (LAND)',
    checkout_phone_label: 'KONTAKTNETZWERK (TELEFON)',
    checkout_validate_btn: 'KOORDINATEN VALIDIEREN',
    checkout_shipping_promise: 'Logistiknetzwerke garantieren den Einsatz so schnell wie möglich.',
    checkout_inventory_title: 'IN IHREM INVENTAR',
    checkout_subtotal_label: 'Zwischensumme',
    checkout_shipping_label: 'Transferfracht',
    checkout_total_label: 'Physisches Gesamt',
    checkout_qty: 'MENGE',
    checkout_size: 'GRÖẞE',
    checkout_success_title: 'ÜBERTRAGUNG BESTÄTIGT',
    checkout_success_desc: 'Ihre Koordinaten wurden assimiliert. Taktische Assets sind unterwegs.',
    checkout_back_system: 'ZUM SYSTEM ZURÜCKKEHREN',
    checkout_back_cart: 'ZURÜCK ZUM WARENKORB',

`
};

content = content.replace(/(en: \{[\s\S]*?)(    story_title:)/, '$1' + keys.en + '$2');
content = content.replace(/(es: \{[\s\S]*?)(    story_title:)/, '$1' + keys.es + '$2');
content = content.replace(/(fr: \{[\s\S]*?)(    story_title:)/, '$1' + keys.fr + '$2');
content = content.replace(/(de: \{[\s\S]*?)(    story_title:)/, '$1' + keys.de + '$2');

fs.writeFileSync(p, content);
console.log("Injected translations successfully.");
